version: '3'
services:
  tfmigrate:
    build:
      context: .
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION:-latest}
    volumes:
      - ".:/work"
    environment:
      CGO_ENABLED: 0 # disable cgo for go test
      LOCALSTACK_ENDPOINT: "http://localstack:4566"
      # Use the same filesystem to avoid a checksum mismatch error
      # or a file busy error caused by asynchronous IO.
      TF_PLUGIN_CACHE_DIR: "/tmp/plugin-cache"
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:0.14.4
    ports:
      - "4566:4566"
    environment:
      DEBUG: "true"
      SERVICES: "s3,ec2,iam"
      DEFAULT_REGION: "ap-northeast-1"
      S3_BUCKET: "tfstate-test"
    volumes:
      - "./scripts/localstack:/docker-entrypoint-initaws.d"  # initialize scripts on startup

  dockerize:
    image: powerman/dockerize:0.16.0
    depends_on:
      - localstack
