version: '3'
services:
  tfmigrate:
    build:
      context: .
      args:
        TERRAFORM_VERSION: 0.12.28
    volumes:
      - ".:/work"
    environment:
      TF_PLUGIN_CACHE_DIR: "/work/tmp/plugin-cache"
      LOCALSTACK_ENDPOINT: "http://localstack:4566"
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:0.11.3
    ports:
      - "4566:4566"
    environment:
      DEBUG: "true"
      SERVICES: "s3,ec2,iam"
      DEFAULT_REGION: "ap-northeast-1"
    volumes:
      - "./scripts/localstack:/docker-entrypoint-initaws.d"  # initialize scripts on startup
