version: '3'
services:
  tfmigrate:
    build:
      context: .
      args:
        TERRAFORM_VERSION: ${TERRAFORM_VERSION:-latest}
    volumes:
      - ".:/work"
    environment:
      CGO_ENABLED: 0 # disable cgo for go test
      TF_PLUGIN_CACHE_DIR: "/tmp"
      LOCALSTACK_ENDPOINT: "http://localstack:4566"
    depends_on:
      - localstack

  localstack:
    image: localstack/localstack:0.11.3
    ports:
      - "4566:4566"
    environment:
      DEBUG: "true"
      SERVICES: "s3,ec2,iam"
      DEFAULT_REGION: "ap-northeast-1"
      S3_BUCKET: "tfstate-test"
    volumes:
      - "./scripts/localstack:/docker-entrypoint-initaws.d"  # initialize scripts on startup
